name: Build and Push to IPFS

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        # - name: Set IMAGE_TAG
        #   run: echo "IMAGE_TAG=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

        # - name: Build image
        #   id: docker_build
        #   run: |
        #     docker build --file Dockerfile --tag $IMAGE_TAG .

        # - name: Store IPFS hash reference
        #   id: ipfs_hash
        #   if: startsWith(github.ref, 'refs/tags/')
        #   run: |
        #     echo "IPFS_HASH=$(docker run --entrypoint /bin/sh $IMAGE_TAG -c 'cat /ipfs_hash.txt')" >> $GITHUB_ENV

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_URL: "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
        run: |
          echo ${{ github.event }} | jq -r "."
          echo $RELEASE_URL
