name: Build and Push to IPFS

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main
    # Publish `v100` tags as releases.
    tags:
      - v*

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build --file Dockerfile --tag $IMAGE_TAG .

      - name: Store IPFS hash reference
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "IPFS_HASH=$(docker run --entrypoint /bin/sh $IMAGE_TAG -c 'cat /ipfs_hash.txt')" >> $GITHUB_ENV

          # - name: Generate and store release note
          #   if: startsWith(github.ref, 'refs/tags/')
          #   run: |
          #     RELEASE=$(curl --location --silent --request POST \
          #       --header "Accept: application/vnd.github+json" \
          #       --header "Authorization: Bearer <YOUR-TOKEN>" \
          #       --header "X-GitHub-Api-Version: 2022-11-28" \
          #       "https://api.github.com/repos/${{ github.repository }}/releases/generate-notes" \
          #       --data "{\"tag_name\":\"${{ github.ref_name }}\",\"target_commitish\":\"main\"}")

          #     # store notes in environment
          #     echo "RELEASE_NOTE_NAME=$(echo $RELEASE | jq -r '.name'" >> $GITHUB_ENV
          #     echo "RELEASE_NOTE_BODY=$(echo $RELEASE | jq -r '.body'" >> $GITHUB_ENV

      - name: Create a draft release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            --silent \
            --location \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer $GITHUB_TOKEN" \
            --header "X-GitHub-Api-Version:  2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/releases" \
            --data "{\"tag_name\":\"${{ github.ref_name }}\",\"target_commitish\":\"main\",\"name\":\"$RELEASE_NOTE_NAME\",\"body\":\"$IPFS_HASH\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true}"
